######### NORMAL OPERATION  ###########

### Read all pizzas
GET http://localhost:3000/questions

### Read pizza identified by 3,2 doesn't exist
GET http://localhost:3000/questions/3

###Read question by random int

GET http://localhost:3000/questions/{{$randomInt 1 4}}