######### NORMAL OPERATION  ###########

### Read all salons
GET http://localhost:3000/salons

### Read pizza identified by 3,2 doesn't exist
GET http://localhost:3000/salons/1


### Create a salon
POST http://localhost:3000/salons



###Ajouter un joueur au salon
PUT http://localhost:3000/salons/addPlayer/1/15


###get players of a salon
GET http://localhost:3000/salons/getPlayers/15

